### ISSUE TITLE
HHVM:  Call to undefined method …TemplateLocator::isFresh

### ISSUE THREAD

**Issue by baptistedonaux** [symfony/assetic-bundle#285]
I have open an issue in facebook/hhvm#2215 because I have an error when I want execute Symfony with HHVM.

This is my error :

```
Fatal error: Call to undefined method Symfony\\Bundle\\FrameworkBundle\\Templating\\Loader\\TemplateLocator::isFresh from context Symfony\\Bundle\\AsseticBundle\\Factory\\Resource\\FileResource in /home/baptiste/Projet/cren/vendor/symfony/assetic-bundle/Symfony/Bundle/AsseticBundle/Factory/Resource/FileResource.php on line 49
```

After search in the code, I have  found the code. Symfony\Bundle\AsseticBundle\Factory\Resource\FileResource take in its constructor, a first argument which implements Symfony\Component\Templating\Loader\LoaderInterface but I didn't understand why I have this error.

**Comment by fpapadopou** [comment]
Any idea on that? I'm getting the same error too. Seems pretty weird because the `loader` provided to the FileResource class is not a `LoaderInterface` object but a `FileLocatorInterface` instead. Does that have to do with AsseticBundle itself or should I look for the cause of the problem somewhere else?

**Comment by stof** [comment]
it would be great to look for the cause of the problem, to understand where it comes from.

**Comment by fpapadopou** [comment]
@stof I'm not sure about the exact steps that can lead to this error. 
I'm not even using HHVM, I'm using Travis CI with PHP 5.5.9. 
I stumbled upon this while trying to access my web app from CasperJS testing framework. Functional tests with PHPUnit **don't** have this issue.

**Comment by Lowkey2224** [comment]
I have the same Problem. I am using Nginx 1.4.6 with HHVM 3.12.1
I can confirm this Problem doesnt bother PHPunit (run with HHVM).
I habe the problem when i just want to access the app_dev.php or app.php 
Is there any progress on this one?
