### ISSUE TITLE
include fail 2.6.0

### ISSUE THREAD

**Issue by mickaelCOLLET** [symfony/assetic-bundle#346]
this fail in version 2.6.0:

{% include app.environment == 'prod' ? '::analytics.html.twig' ignore missing %}

An exception has been thrown during the rendering of a template ("Warning: file_get_contents(***\app\Resources\views): failed to open stream: Permission denied")

**Comment by stof** [comment]
Please paste the stack trace of the exception and explain in which case you get this error (there is nothing related to AsseticBundle in your current report)
