### ISSUE TITLE
Allowing Symfony 3 components

### ISSUE THREAD

**Issue by TomasVotruba** [symfony/assetic-bundle#374]
Before sending PR I want to ask first. Is there some related issue to not to allow Symfony 3 components?

This is one of few places, that disallows to try project running on Symfony 3.

**Comment by stof** [comment]
The reason is that Symfony 3 is not yet ready, and I know we will still have some BC breaks related to the Templating component, which will affect this bundle (and until a few hours ago, the bundle was broken on Symfony 3 btw)

**Comment by TomasVotruba** [comment]
@stof I know it was broken, because I'm building Symfony 3 sandbox and this is one of few packages that is not compatible (doesn't allow Symfony 3 and/or buggy with it).

That's why I want allow it and to add a test suite for Symfony 3.

**Comment by stof** [comment]
Allowing the testsuite on Symfony 3 can be done with some tricks, without actually allowing it for real if it does not work yet

**Comment by TomasVotruba** [comment]
This bundle is not part of Symfony demo anymore so the issue is not relevant anymore.
