### ISSUE TITLE
Autoprefixer (6.0+) filter broken

### ISSUE THREAD

**Issue by samsch** [symfony/assetic-bundle#384]
The Autoprefixer CLI has been [moved to](https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md#60-eureka) [autoprefixer-cli](https://www.npmjs.com/package/autoprefixer-cli) for legacy support. The new recommended approach is to use PostCSS with autoprefixer.

To fix this in assetic, the filter would need to be re-written to use PostCSS, and it might need some extra documentation.

To work around this for now, you can use `bin: /[path-to-bins]/autoprefixer-cli` in config.

**Comment by stof** [comment]
Closing as the solution for now is indeed to use the autoprefixer-cli package for now (or keeping using 5.x).

Using postcss would be a different filter, and the bundle is the wrong place to ask for it.
