### ISSUE TITLE
app/console assetic:dump throws error with Twig v1.22.x

### ISSUE THREAD

**Issue by angelsk** [symfony/assetic-bundle#385]
> app/console assetic:dump                                                                  
  [LogicException]                                                             
  Cache can only be a string, false, or a Twig_CacheInterface implementation.  

Currently fixed twig @ (v1.21.2) to fix for now.

Using kriswallsmith/assetic:v1.3.0, "symfony/assetic-bundle": "~2.3",

**Comment by stof** [comment]
Please paste the stack trace of the exception, otherwise it will be very hard to fix it.

**Comment by angelsk** [comment]
That's all I get from the command line.

[deploy@jo-dev current]$ app/console assetic:dump
                                                              
  [LogicException]                                                             
  Cache can only be a string, false, or a Twig_CacheInterface implementation.  
                                                                               
assetic:dump [--forks FORKS] [--watch] [--force] [--period PERIOD] [--] [<write_to>]

**Comment by stof** [comment]
Run the command in verbose mode to get the stack trace

**Comment by angelsk** [comment]
Ahh..

````
Exception trace:
 () at /srv/www/dev_site/current/vendor/twig/twig/lib/Twig/Environment.php:269
 Twig_Environment->setCache() at /srv/www/dev_site/current/vendor/twig/twig/lib/Twig/Environment.php:114
 Twig_Environment->__construct() at /dev/shm/dev_site/tmp/cache/dev/appDevDebugProjectContainer.php:3446
 appDevDebugProjectContainer->getTwigService() at /srv/www/dev_site/current/app/bootstrap.php.cache:2155
 Symfony\Component\DependencyInjection\Container->get() at /dev/shm/dev_site/tmp/cache/dev/appDevDebugProjectContainer.php:348
 appDevDebugProjectContainer->getAssetic_AssetManagerService() at /srv/www/dev_site/current/app/bootstrap.php.cache:2155
 Symfony\Component\DependencyInjection\Container->get() at /srv/www/dev_site/current/vendor/symfony/assetic-bundle/Command/AbstractCommand.php:28
 Symfony\Bundle\AsseticBundle\Command\AbstractCommand->initialize() at /srv/www/dev_site/current/vendor/symfony/assetic-bundle/Command/DumpCommand.php:64
 Symfony\Bundle\AsseticBundle\Command\DumpCommand->initialize() at /srv/www/dev_site/current/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:238
 Symfony\Component\Console\Command\Command->run() at /srv/www/dev_site/current/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/dev_site/current/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /srv/www/dev_site/current/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/www/dev_site/current/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /srv/www/dev_site/current/app/console:27
````

**Comment by stof** [comment]
Well, this seems a wrong configuration of your ``twig`` service, which means an issue in TwigBundle directly. This stack trace confirms me that the error occurs when getting twig from the container, and AsseticBundle is not responsible for configuring Twig.

**Comment by stof** [comment]
Can you show your ``twig`` configuration though ?

**Comment by angelsk** [comment]
I'm using the default configuration of twig.

**Comment by xabbuh** [comment]
@angelsk Can you provide a fork of the Symfony Standard Edition that reproduces your issue?
