### ISSUE TITLE
Yaml ParseException in config file with extension-based filter

### ISSUE THREAD

**Issue by Flo-Schield-Bobby** [symfony/assetic-bundle#397]
I just switched to SF3, which includes ````symfony/yaml```` ````3.0````

As specified in the [official documentation](https://symfony.com/doc/current/cookbook/assetic/apply_to_option.html#filtering-based-on-a-file-extension),
I would like to set the scss filter on all scss files, based on the extension :

    assetic:
        # [...]
        filters:
            scss:
                apply_to: "\.scss$"

And I receive an error while parsing the ````app/config/config.yml```` file :

    [Symfony\Component\Yaml\Exception\ParseException]
    Found unknown escape character "\." at line 53 (near "apply_to: "\.scss$"").

Not sure if this issue is related to Assetic or Yaml.

**Comment by Phobetor** [comment]
@Flo-Schield-Bobby You need to escape `\`characters when surrounded by double-quotes as described in the upgrade guide to synfony 3.0: https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#yaml

This should work:
```yml
assetic:
    # [...]
    filters:
        scss:
            apply_to: "\\.scss$"
```

**Comment by Flo-Schield-Bobby** [comment]
Ah, thanks, I missed this part of the upgrade guide.
I'll see if I can PR the documentation :)

Works with single quotes too.

    assetic:
        # [...]
        filters:
            scss:
                apply_to: '\.scss$'

**Comment by xabbuh** [comment]
@Flo-Schield-Bobby The reason for that is that escape sequences (which start with a backslash) are only supported inside of double quotes in YAML and why you need to escape backslashes there. By the way, can you close here please now that your issue is solved?
