### ISSUE TITLE
Tag 2.8 version

### ISSUE THREAD

**Issue by metfan** [symfony/assetic-bundle#401]
Hello, 

Is it possible to have a tag 2.8 to follow sf version?

thanks

**Comment by stof** [comment]
I will tag a new release this weekend. But it will probably be a 2.7.2 as there is no new feature in it, just a bugfix for the Symfony 3 compat.

The release process of this bundle is decoupled from the main repo, meaning there is no reason to synchronize version numbers (for instance, I have no reason to make a new major version of the bundle any time soon)

**Comment by BallisticPain** [comment]
@stof can we get an updated release? Is there something I can do to help?

I'm trying to update to SF2.8, but Assetic is being a pain, and on top of that when removing it ... the pain doesn't disappear... sooooo... help please!

Thanks!

**Comment by xabbuh** [comment]
@BallisticPain For the moment I suggest to rely on a development version of AsseticBundle. But I am sure that @stof will create a new release soon.

**Comment by COil** [comment]
Interested by the tag too. :+1:

**Comment by stof** [comment]
I want to check the Symfony3 compat fully before releasing, as the previous release had a bunch of issues. This will have to wait at least a few days (I have other plans for this evening)

**Comment by COil** [comment]
No problem @stof , it can wait 2016 ;)

**Comment by Wirone** [comment]
Any news? We're waiting too for this release.

**Comment by gremo** [comment]
Please we need a new release!

**Comment by mickaelandrieu** [comment]
@stof can we help you ?

**Comment by Taluu** [comment]
ping @stof for a release

**Comment by cesco69** [comment]
For more than a month there is no version, Shall we still rely on assetic-bundle?

**Comment by cesco69** [comment]
@stof

**Comment by luispabon** [comment]
Any news on this?

**Comment by jewome62** [comment]
I wait for this too ;D

:beer:

**Comment by lbayerl** [comment]
+1

**Comment by roundge** [comment]
me too ^^

**Comment by c960657** [comment]
Guys, please do not post any more "+1" or "any news?" comments. I'm sure @stof is well aware that this is a popular ticket and that he will see to it soon. All these comments just add annoying noise to the issue and to the inbox of everybody subscribing to this issue. Chill, and good things will happen :smile:

**Comment by surivrox** [comment]
@stof how can we help to make it done?

**Comment by BertrandD** [comment]
:+1:

**Comment by arisro** [comment]
We badly need this - we really want to upgrade in prod to sf 2.8 cleanly :+1:

**Comment by peter17** [comment]
@stof Is there anything we can do to help? We are a lot of people here needing a 2.7.2 or a 2.8 tag and we have been waiting for months... See #395. Thanks a lot!

**Comment by succinct** [comment]
Any update on this? We'd love to get this updated, as it's the last deprecation left in our project.

**Comment by Holmesologie** [comment]
@symfony please do something

**Comment by stephanvierkant** [comment]
@fabpot This is getting really annoying. We need an update on this issue.

**Comment by fabpot** [comment]
I can understand that this is annoying but then again, I'm not in charge of this bundle, nothing I can do really except pinging @stof @kriswallsmith; can you make a release?

**Comment by kriswallsmith** [comment]
@stof are we ready to tag `v2.8.0` or is there something pending?

**Comment by MatTheCat** [comment]
I see [2.8.0 in packagist](https://packagist.org/packages/symfony/assetic-bundle) even though it seems this tag doesn't exist. What happened?

**Comment by kriswallsmith** [comment]
That was my mistake. I've pushed the tag for 2.8.0.

**Comment by BallisticPain** [comment]
@kriswallsmith Thanks for your assistance!
@stof Thanks for your hard work and assistance!

**Comment by f18n** [comment]
I install composer require symfony/assetic-bundle than use symfony\..assetic.. than config.yml this error why #Symfony 3.0

**Comment by xabbuh** [comment]
@f18n Please open a new issue and provide sind more information to what you refer with "this error".
