### ISSUE TITLE
The service "assetic.helper.static" has a dependency on a non-existent service "assets.packages".

### ISSUE THREAD

**Issue by xtazy** [symfony/assetic-bundle#406]
Hi,

The bundle is not compatible anymore with symonfy 2.6 because of this commit : https://github.com/symfony/assetic-bundle/commit/820093cd91c3c40a39ecde4e343764c18630b9ce

Indeed, in the Resources/config/templating_php.xml file, the service **assets.packages** doesn't exist.

Best regards.

**Comment by xabbuh** [comment]
But if the `assets.packages` service does not exist, the compiler pass will replace the argument and inject the `templating.helper.assets` service instead.

**Comment by xtazy** [comment]
I agree, but the StaticAsseticHelperPass is not added to the container in the AsseticBundle.php file. So this compiler pass is not called and the good service is not injected.

**Comment by xabbuh** [comment]
see #407

**Comment by xtazy** [comment]
Thanks :)
