### ISSUE TITLE
Using Twig asset function for a folder

### ISSUE THREAD

**Issue by morille** [symfony/assetic-bundle#417]
I'm using CKEditor in one of my projects and it requires to setup a base path, from where it will load plugins, themes, etc.
I would like to use assetic to generate the URL of this folder so it's not hardcoded in JS.

Basically this works with the current Twig "asset" function:
```javascript
var CKEDITOR_BASEPATH = "{{ asset('bundles/acme/vendor/ckeditor') }}";
// => var CKEDITOR_BASEPATH = "/bundles/acme/vendor/ckeditor";
```

Until I set the "framework/asset/version" configuration of my project:
```
framework:
    assets:
        version: 21
```

Then of course:

```javascript
var CKEDITOR_BASEPATH = "{{ asset('bundles/acme/vendor/ckeditor') }}";
// => var CKEDITOR_BASEPATH = "/bundles/acme/vendor/ckeditor?21";
```

I think it could be useful to have another argument for the "asset" function to disable the asset number functionnality.

**Comment by xabbuh** [comment]
@morille You are confusing Assetic, which is configured under the `assetic` key, and the Symfony Asset component (configured with the `framework.assets` options). When using the Asset component (like you do), you can configure different [packages](http://symfony.com/doc/current/reference/configuration/framework.html#packages) all having their own versions (or even no version).

**Comment by morille** [comment]
@xabbuh Indeed I'm not posting on the right repo, sorry. And many thanks you for your answer, exactly what I need.
