### ISSUE TITLE
Cannot load css file by aset()

### ISSUE THREAD

**Issue by arczi87** [symfony/assetic-bundle#422]
I have an issue with loading css files on twig template using asset Symfony 3
My css file is placed in **web/css/main.css** directory. I installed asetic-boundle module and switched it in config.yml.

```twig
{%stylesheet
    <link rel="stylesheet" href="{{ asset('css/main.css') }}" />
{ endstylesheets %}
 <link rel="icon" href="{{ asset('favicon.ico') }}" type="image/x-icon">
```

In browser console get info : 
Cannot load resource : http://mylocalhostdomain.com/css/main.css

**Comment by stof** [comment]
the ``{% stylesheet %}`` tag you gave in your code snippet does not make any sense, as you never render the URL of the Assetic asset.

On a side note, ``asset()`` itself has nothing to do with Assetic. It is coming from the Symfony Asset component.

**Comment by arczi87** [comment]
This also happens when I try this way :
`<link rel="stylesheet" href="css/main.css" />`

Soo how should I load the css files from web directory ?

**Comment by stof** [comment]
if you just want to load your CSS file, ``<link rel="stylesheet" href="{{ asset('css/main.css') }}" />```is what you need in Symfony. But without putting a ``{% stylesheet %}`` tag around them, as Assetic has no reason to be impacted if you just want to reference your file directly. And then, it means this issue tracker is not the right place.
