### ISSUE TITLE
Define assets in config results in 500 error on first load

### ISSUE THREAD

**Issue by silverbackdan** [symfony/assetic-bundle#429]
On the first load after clearing the cache with no warmup in a production environment the following error is given:
`[2017-02-15 15:34:04] request.CRITICAL: Uncaught PHP Exception Twig_Error_Syntax: "Lexer or parser ended up in unsupported state." at *** line 2 {"exception":"[object] (Twig_Error_Syntax(code: 0): Lexer or parser ended up in unsupported state. at ***:2)"} []`

Config definition
```yaml
assetic:
    assets:
        BaseJS:
            inputs:
                - '@AppBundle/Resources/private/***.js'
```

It's also been posted on Stack Exchange here:
http://stackoverflow.com/questions/37767249/symfony3-twig-assetic-parsing-error/42253880#42253880

The page will work and load after a refresh. It may also be related to using a custom versioning strategy although I don't think so. If so, I am using this bundle:
https://github.com/irozgar/gulp-rev-versions-bundle

I've configured my gulp.js and the manifest is being populated, also on the refresh the paths are correct with the revisions.

**Comment by stof** [comment]
Why are you using Assetic if you have a gulp-based build system ? Just perform the concatenation of files with Gulp too, and reference the asset with ``asset()``.

**Comment by silverbackdan** [comment]
I began with just trying to configure a Gulp based system, but it became complicated quickly and added too much complexity I thought. I'd rather define my assets for each page in a Twig template and keep a simple and well documented workflow. The only thing I really would like is a revisions system which generates a hash based on file contents instead of forcing a cache refresh on every asset based on a simple version number.

I didn't think the versioning strategy was causing this problem in any case.

I suppose I could create a bundle with a Twig extension to define files for Gulp to process which I did do originally. But it got very complicated and wanted to opt for a widely used and stable solution, especially as I'm new to both Symfony and Gulp so am likely to keep making silly errors.

I'm always happy to discuss and learn though, especially if there's a workflow you'd recommend.

**Comment by stof** [comment]
but gulp won't help you in this case: you would have to version the final file, not the input file.

do you have the same error if you don't involve your custom version strategy ?

**Comment by silverbackdan** [comment]
I hope I'm not being too stupid (though it's very possible!) I dump all the assets with Assetic then version the dumped files. Here is a little Gist with my setup (without defining assets in the config.yml fie):
https://gist.github.com/silverbackdan/d20e01b7d13bf32df7c5fa5fd6de0f62
I just added a simple bash script to run the dump and versioning when I need to make it live.

I've just done a test by commenting out the versioning strategy, defining assets:
```yaml
assets:
        BaseCSS:
            inputs:
                - '@AppBundle/Resources/private/bootstrap/bootstrap.scss'
```
And then referencing in the twig template:
```twig
{% stylesheets 
        '@BaseCSS'
        filter='compass'
        filter='cssrewrite'
        filter='?uglifycss'
         %}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
```

The error is the same.

**Comment by silverbackdan** [comment]
Sorry, one other thing I don't think I was clear before, but this only happens in a production environment it seems. So for the sake of clarity the steps to reproduce would be:
* Define assets in config
* Use the defined assets in a twig template
* Clear the production cache with --no-warmup
* First load gives the 500 error

**Comment by touiliy** [comment]
I have the exact same error :/

**Comment by samirspatel** [comment]
Getting the same issue here, not sure why this is happening. "Lexer or parser ended up in unsupported state"

**Comment by jarofgreen** [comment]
I have also seen this, but oddly in Dev not Production. And just now I sat down to try and reproduce, and it's all started working fine! (I'm not using gulp in any way at all, to be clear)

**Comment by silverbackdan** [comment]
I think it's about time I close this issue. I'm not using Assetic anymore so won't be much help. If others are having this issue it's probably best to raise a new issue.
